const items = [
    {"id": 1, "name": "Ahsanullah University of Science and Technology"},
    {"id": 2, "name": "American International University-Bangladesh"},
    {"id": 3, "name": "Anwer Khan Modern University"},
    {"id": 4, "name": "ASA University Bangladesh"},
    {"id": 5, "name": "Asian University for Women"},
    {"id": 6, "name": "Asian University of Bangladesh"},
    {"id": 7, "name": "Atish Dipankar University of Science and Technology"},
    {"id": 8, "name": "Bandarban University"},
    {"id": 9, "name": "Bangabandhu Sheikh Mujib Medical University"},
    {"id": 10, "name": "Bangabandhu Sheikh Mujibur Rahman Agricultural University"},
    {"id": 11, "name": "Bangabandhu Sheikh Mujibur Rahman Maritime University"},
    {"id": 12, "name": "Bangabandhu Sheikh Mujibur Rahman Science and Technology University"},
    {"id": 13, "name": "Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University"},
    {"id": 14, "name": "Bangladesh Agricultural University"},
    {"id": 15, "name": "Bangladesh Islami University"},
    {"id": 16, "name": "Bangladesh University"},
    {"id": 17, "name": "Bangladesh University of Business and Technology"},
    {"id": 18, "name": "Bangladesh University of Engineering and Technology"},
    {"id": 19, "name": "Bangladesh University of Health Sciences"},
    {"id": 20, "name": "Bangladesh University of Professionals"},
    {"id": 21, "name": "Bangladesh University of Textiles"},
    {"id": 22, "name": "Begum Gulchemonara Trust University"},
    {"id": 23, "name": "Begum Rokeya University"},
    {"id": 24, "name": "BGMEA University of Fashion and Technology"},
    {"id": 25, "name": "BRAC University"},
    {"id": 26, "name": "Britannia University"},
    {"id": 27, "name": "Canadian University of Bangladesh"},
    {"id": 28, "name": "CCN University of Science and Technology"},
    {"id": 29, "name": "Central University of Science and Technology"},
    {"id": 30, "name": "Central Women's University"},
    {"id": 31, "name": "Chittagong Independent University"},
    {"id": 32, "name": "Chittagong Medical University"},
    {"id": 33, "name": "Chittagong University of Engineering and Technology"},
    {"id": 34, "name": "Chittagong Veterinary and Animal Sciences University"},
    {"id": 35, "name": "City University"},
    {"id": 36, "name": "Comilla University"},
    {"id": 37, "name": "Cox's Bazar International University"},
    {"id": 38, "name": "Daffodil International University"},
    {"id": 39, "name": "Dhaka International University"},
    {"id": 40, "name": "Dhaka University of Engineering and Technology"},
    {"id": 41, "name": "East Delta University"},
    {"id": 42, "name": "East West University"},
    {"id": 43, "name": "Eastern University"},
    {"id": 44, "name": "European University of Bangladesh"},
    {"id": 45, "name": "Exim Bank Agricultural University of Bangladesh"},
    {"id": 46, "name": "Fareast International University"},
    {"id": 47, "name": "Feni University"},
    {"id": 48, "name": "First Capital University of Bangladesh"},
    {"id": 49, "name": "German University Bangladesh"},
    {"id": 50, "name": "Global University Bangladesh"},
    {"id": 51, "name": "Gono Bishwabidyalay"},
    {"id": 52, "name": "Green University of Bangladesh"},
    {"id": 53, "name": "Hajee Mohammad Danesh Science and Technology University"},
    {"id": 54, "name": "Hamdard University of Bangladesh"},
    {"id": 55, "name": "IBAIS University"},
    {"id": 56, "name": "Independent University"},
    {"id": 57, "name": "International Islamic University"},
    {"id": 58, "name": "International Standard University"},
    {"id": 59, "name": "International University of Business Agriculture and Technology"},
    {"id": 60, "name": "Ishakha International University"},
    {"id": 61, "name": "Islamic Arabic University"},
    {"id": 62, "name": "Islamic University"},
    {"id": 63, "name": "Islamic University of Technology"},
    {"id": 64, "name": "Jagannath University"},
    {"id": 65, "name": "Jahangirnagar University"},
    {"id": 66, "name": "Jatiya Kabi Kazi Nazrul Islam University"},
    {"id": 67, "name": "Jessore University of Science and Technology"},
    {"id": 68, "name": "Khulna Agricultural University"},
    {"id": 69, "name": "Khulna University"},
    {"id": 70, "name": "Khulna University of Engineering and Technology"},
    {"id": 71, "name": "Khwaja Yunus Ali University"},
    {"id": 72, "name": "Leading University"},
    {"id": 73, "name": "Manarat International University"},
    {"id": 74, "name": "Mawlana Bhashani Science and Technology University"},
    {"id": 75, "name": "Metropolitan University"},
    {"id": 76, "name": "N.P.I. University of Bangladesh"},
    {"id": 77, "name": "National University"},
    {"id": 78, "name": "Noakhali Science and Technology University"},
    {"id": 79, "name": "North Bengal International University"},
    {"id": 80, "name": "North East University Bangladesh"},
    {"id": 81, "name": "North South University"},
    {"id": 82, "name": "North Western University"},
    {"id": 83, "name": "Northern University of Bangladesh"},
    {"id": 84, "name": "Northern University of Business and Technology"},
    {"id": 85, "name": "Notre Dame University Bangladesh"},
    {"id": 86, "name": "Pabna Science and Technology University"},
    {"id": 87, "name": "Patuakhali Science and Technology University"},
    {"id": 88, "name": "Port City International University"},
    {"id": 89, "name": "Premier University"},
    {"id": 90, "name": "Presidency University"},
    {"id": 91, "name": "Prime University"},
    {"id": 92, "name": "Primeasia University"},
    {"id": 93, "name": "Pundra University of Science and Technology"},
    {"id": 94, "name": "Queens University"},
    {"id": 95, "name": "Rabindra Maitree University"},
    {"id": 96, "name": "Rabindra University"},
    {"id": 97, "name": "Rajshahi Medical University"},
    {"id": 98, "name": "Rajshahi Science and Technology University"},
    {"id": 99, "name": "Rajshahi University"},
    {"id": 100, "name": "Rajshahi University of Engineering and Technology"},
    {"id": 101, "name": "Ranada Prasad Shaha University"},
    {"id": 102, "name": "Rangamati Science and Technology University"},
    {"id": 103, "name": "Royal University of Dhaka"},
    {"id": 104, "name": "Shahjalal University of Science and Technology"},
    {"id": 105, "name": "Shanto Mariam University of Creative Technology"},
    {"id": 106, "name": "Sheikh Fazilatunnesa Mujib University"},
    {"id": 107, "name": "Sheikh Hasina University"},
    {"id": 108, "name": "Sher-e-Bangla Agricultural University"},
    {"id": 109, "name": "Sonargaon University"},
    {"id": 110, "name": "Southeast University"},
    {"id": 111, "name": "Southern University Bangladesh"},
    {"id": 112, "name": "Stamford University Bangladesh"},
    {"id": 113, "name": "State University of Bangladesh"},
    {"id": 114, "name": "Sylhet Agricultural University"},
    {"id": 115, "name": "Sylhet International University"},
    {"id": 116, "name": "Sylhet Medical University"},
    {"id": 117, "name": "The International University of Scholars"},
    {"id": 118, "name": "The Millenium University"},
    {"id": 119, "name": "The People's University of Bangladesh"},
    {"id": 120, "name": "Times University of Bangladesh"},
    {"id": 121, "name": "United International University"},
    {"id": 122, "name": "University of Asia Pacific"},
    {"id": 123, "name": "University of Barisal"},
    {"id": 124, "name": "University of Chittagong"},
    {"id": 125, "name": "University of Creative Technology"},
    {"id": 126, "name": "University of Development Alternative"},
    {"id": 127, "name": "University of Dhaka"},
    {"id": 128, "name": "University of Global Village"},
    {"id": 129, "name": "University of Information Technology and Sciences"},
    {"id": 130, "name": "University of Liberal Arts Bangladesh"},
    {"id": 131, "name": "University of Science and Technology Chittagong"},
    {"id": 132, "name": "University of South Asia"},
    {"id": 133, "name": "Uttara University"},
    {"id": 134, "name": "Varendra University"},
    {"id": 135, "name": "Victoria University of Bangladesh"},
    {"id": 136, "name": "World University of Bangladesh"},
    {"id": 137, "name": "Z.H. Sikder University of Science and Technology"},
    {"id": 138, "name": "ZNRF University of Management Sciences"}
]
export default items;