name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER_NAME }}
          password: ${{ secrets.DIGITAL_OCEAN_DEPLOY_KEY }}
          port: 22
          script: |
            cd /path/to/your/react/app
            git pull origin main
            npm install
            npm run build
            sudo mv build /var/www/html/ncpcfrontend
