on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22

      - name: 📂 Move to deployment directory
        run: |
          ssh ${{ secrets.FTP_USER }}@${{ secrets.FTP_SERVER }} -p 22 "cd /path/to/your/deployment/directory && mkdir -p ./build"

      - name: 📂 Deploy files
        run: |
          scp -r ./build/* ${{ secrets.FTP_USER }}@${{ secrets.FTP_SERVER }}:/path/to/your/deployment/directory/build
